import { Router, Request, Response, NextFunction } from 'express';
import { z } from 'zod';
import { prisma } from '../db.js';
import { validate } from '../middleware/validate.js';
import { AppError } from '../middleware/errorHandler.js';

const router = Router();

function asyncHandler(fn: (req: Request, res: Response, next: NextFunction) => Promise<void>) {
  return (req: Request, res: Response, next: NextFunction) => {
    fn(req, res, next).catch(next);
  };
}

const createLabelSchema = z.object({
  type: z.enum(['dietary', 'allergen', 'equipment', 'makeAhead']),
  name: z.string().min(1).max(100),
  autoDetectable: z.boolean().default(false),
});

const assignLabelsSchema = z.object({
  labelIds: z.array(z.string()),
});

const assignCategoriesSchema = z.object({
  categoryIds: z.array(z.string()),
});

// GET /api/labels
router.get(
  '/',
  asyncHandler(async (req, res) => {
    const type = req.query.type as string | undefined;
    const where = type ? { type } : {};
    const labels = await prisma.label.findMany({
      where,
      orderBy: [{ type: 'asc' }, { name: 'asc' }],
    });
    res.json(labels);
  }),
);

// POST /api/labels
router.post(
  '/',
  validate(createLabelSchema),
  asyncHandler(async (req, res) => {
    const label = await prisma.label.create({
      data: req.body,
    });
    res.status(201).json(label);
  }),
);

// POST /api/recipes/:id/labels — assign labels to a recipe
router.post(
  '/recipes/:id/labels',
  validate(assignLabelsSchema),
  asyncHandler(async (req, res) => {
    const { id } = req.params;
    const { labelIds } = req.body;

    const recipe = await prisma.recipe.findUnique({ where: { id } });
    if (!recipe) throw new AppError(404, 'Recipe not found');

    // Remove existing labels and add new ones
    await prisma.$transaction([
      prisma.recipeLabel.deleteMany({ where: { recipeId: id } }),
      ...labelIds.map((labelId: string) =>
        prisma.recipeLabel.create({
          data: { recipeId: id, labelId, isAutoGenerated: false },
        }),
      ),
    ]);

    const updated = await prisma.recipe.findUnique({
      where: { id },
      include: {
        labels: { include: { label: true } },
        ingredients: { orderBy: { orderIndex: 'asc' } },
        steps: { orderBy: { orderIndex: 'asc' } },
      },
    });

    res.json(updated);
  }),
);

// POST /api/recipes/:id/categories — assign categories to a recipe
router.post(
  '/recipes/:id/categories',
  validate(assignCategoriesSchema),
  asyncHandler(async (req, res) => {
    const { id } = req.params;
    const { categoryIds } = req.body;

    const recipe = await prisma.recipe.findUnique({ where: { id } });
    if (!recipe) throw new AppError(404, 'Recipe not found');

    await prisma.$transaction([
      prisma.recipeCategory.deleteMany({ where: { recipeId: id } }),
      ...categoryIds.map((categoryId: string) =>
        prisma.recipeCategory.create({
          data: { recipeId: id, categoryId },
        }),
      ),
    ]);

    const updated = await prisma.recipe.findUnique({
      where: { id },
      include: {
        categories: { include: { category: true } },
        ingredients: { orderBy: { orderIndex: 'asc' } },
        steps: { orderBy: { orderIndex: 'asc' } },
      },
    });

    res.json(updated);
  }),
);

export default router;
