// Each entry: [canonical lowercase name, allergens[], compatible diets[], default grocery aisle]
// "compatible diets" = diets this ingredient does NOT disqualify
// Allergen and diet values must match ALLERGENS / DIETS constants; aisle must be one of AISLES.
// Aisles are bulk-assigned per section with per-item exceptions (fresh herbs → produce, flours →
// baking-spices, …); anything genuinely ambiguous defaults to 'household-other'.

import type { Aisle } from './aisles.js';

type Entry = [string, string[], string[], Aisle];

const ALL: string[] = ['vegan', 'vegetarian', 'pescatarian', 'gluten_free', 'dairy_free', 'nut_free'];
const VEG_PLUS: string[] = ['vegetarian', 'pescatarian', 'gluten_free', 'dairy_free', 'nut_free']; // not vegan (honey, eggs, etc.)
const VEGAN_NO_GF: string[] = ['vegan', 'vegetarian', 'pescatarian', 'dairy_free', 'nut_free']; // vegan but contains gluten
const MEAT: string[] = ['gluten_free', 'dairy_free', 'nut_free']; // land meat
const SEAFOOD: string[] = ['pescatarian', 'gluten_free', 'dairy_free', 'nut_free']; // fish/shellfish
const DAIRY: string[] = ['vegetarian', 'pescatarian', 'gluten_free', 'nut_free']; // dairy (not vegan/dairy_free)
const EGG: string[] = ['vegetarian', 'pescatarian', 'gluten_free', 'dairy_free', 'nut_free']; // eggs
const NUTS: string[] = ['vegan', 'vegetarian', 'pescatarian', 'gluten_free', 'dairy_free']; // tree nuts / peanuts (not nut_free)

export const INGREDIENT_CATALOG: Entry[] = [
  // ── Proteins ──────────────────────────────────────────────────────────────
  ['bacon', [], MEAT, 'meat-seafood'],
  ['beef steak', [], MEAT, 'meat-seafood'],
  ['chicken breast', [], MEAT, 'meat-seafood'],
  ['chicken thighs', [], MEAT, 'meat-seafood'],
  ['chicken wings', [], MEAT, 'meat-seafood'],
  ['crab', ['shellfish'], SEAFOOD, 'meat-seafood'],
  ['eggs', ['eggs'], EGG, 'dairy-eggs'],
  ['ground beef', [], MEAT, 'meat-seafood'],
  ['ground pork', [], MEAT, 'meat-seafood'],
  ['ground turkey', [], MEAT, 'meat-seafood'],
  ['ham', [], MEAT, 'deli'],
  ['lamb chops', [], MEAT, 'meat-seafood'],
  ['lobster', ['shellfish'], SEAFOOD, 'meat-seafood'],
  ['pork chops', [], MEAT, 'meat-seafood'],
  ['pork loin', [], MEAT, 'meat-seafood'],
  ['salmon', ['fish'], SEAFOOD, 'meat-seafood'],
  ['sausage', [], ['dairy_free', 'nut_free'], 'meat-seafood'], // may contain gluten fillers; not vegetarian
  ['shrimp', ['shellfish'], SEAFOOD, 'meat-seafood'],
  ['tempeh', ['soy'], ALL, 'produce'],
  ['tilapia', ['fish'], SEAFOOD, 'meat-seafood'],
  ['tofu', ['soy'], ALL, 'produce'],
  ['tuna', ['fish'], SEAFOOD, 'meat-seafood'],
  ['turkey breast', [], MEAT, 'meat-seafood'],

  // ── Dairy ─────────────────────────────────────────────────────────────────
  ['butter', ['dairy'], DAIRY, 'dairy-eggs'],
  ['cheddar cheese', ['dairy'], DAIRY, 'dairy-eggs'],
  ['cottage cheese', ['dairy'], DAIRY, 'dairy-eggs'],
  ['cream cheese', ['dairy'], DAIRY, 'dairy-eggs'],
  ['feta cheese', ['dairy'], DAIRY, 'dairy-eggs'],
  ['goat cheese', ['dairy'], DAIRY, 'dairy-eggs'],
  ['greek yogurt', ['dairy'], DAIRY, 'dairy-eggs'],
  ['gruyere cheese', ['dairy'], DAIRY, 'dairy-eggs'],
  ['half and half', ['dairy'], DAIRY, 'dairy-eggs'],
  ['heavy cream', ['dairy'], DAIRY, 'dairy-eggs'],
  ['milk', ['dairy'], DAIRY, 'dairy-eggs'],
  ['mozzarella cheese', ['dairy'], DAIRY, 'dairy-eggs'],
  ['parmesan cheese', ['dairy'], DAIRY, 'dairy-eggs'],
  ['ricotta cheese', ['dairy'], DAIRY, 'dairy-eggs'],
  ['sour cream', ['dairy'], DAIRY, 'dairy-eggs'],
  ['whole milk', ['dairy'], DAIRY, 'dairy-eggs'],
  ['yogurt', ['dairy'], DAIRY, 'dairy-eggs'],

  // ── Vegetables ────────────────────────────────────────────────────────────
  ['artichoke', [], ALL, 'produce'],
  ['arugula', [], ALL, 'produce'],
  ['asparagus', [], ALL, 'produce'],
  ['avocado', [], ALL, 'produce'],
  ['beet', [], ALL, 'produce'],
  ['bell pepper', [], ALL, 'produce'],
  ['broccoli', [], ALL, 'produce'],
  ['brussels sprouts', [], ALL, 'produce'],
  ['butternut squash', [], ALL, 'produce'],
  ['cabbage', [], ALL, 'produce'],
  ['carrot', [], ALL, 'produce'],
  ['cauliflower', [], ALL, 'produce'],
  ['celery', [], ALL, 'produce'],
  ['cherry tomato', [], ALL, 'produce'],
  ['chili pepper', [], ALL, 'produce'],
  ['corn', [], ALL, 'produce'],
  ['cucumber', [], ALL, 'produce'],
  ['eggplant', [], ALL, 'produce'],
  ['fennel', [], ALL, 'produce'],
  ['garlic', [], ALL, 'produce'],
  ['green bean', [], ALL, 'produce'],
  ['green bell pepper', [], ALL, 'produce'],
  ['green onion', [], ALL, 'produce'],
  ['iceberg lettuce', [], ALL, 'produce'],
  ['jalapeño', [], ALL, 'produce'],
  ['kale', [], ALL, 'produce'],
  ['leek', [], ALL, 'produce'],
  ['mushroom', [], ALL, 'produce'],
  ['onion', [], ALL, 'produce'],
  ['pea', [], ALL, 'produce'],
  ['portobello mushroom', [], ALL, 'produce'],
  ['potato', [], ALL, 'produce'],
  ['radish', [], ALL, 'produce'],
  ['red bell pepper', [], ALL, 'produce'],
  ['red onion', [], ALL, 'produce'],
  ['romaine lettuce', [], ALL, 'produce'],
  ['shallot', [], ALL, 'produce'],
  ['shiitake mushroom', [], ALL, 'produce'],
  ['spinach', [], ALL, 'produce'],
  ['squash', [], ALL, 'produce'],
  ['sweet potato', [], ALL, 'produce'],
  ['tomato', [], ALL, 'produce'],
  ['yellow onion', [], ALL, 'produce'],
  ['zucchini', [], ALL, 'produce'],

  // ── Fruits ────────────────────────────────────────────────────────────────
  ['apple', [], ALL, 'produce'],
  ['banana', [], ALL, 'produce'],
  ['blackberry', [], ALL, 'produce'],
  ['blueberry', [], ALL, 'produce'],
  ['cantaloupe', [], ALL, 'produce'],
  ['grape', [], ALL, 'produce'],
  ['lemon', [], ALL, 'produce'],
  ['lime', [], ALL, 'produce'],
  ['mango', [], ALL, 'produce'],
  ['orange', [], ALL, 'produce'],
  ['peach', [], ALL, 'produce'],
  ['pear', [], ALL, 'produce'],
  ['pineapple', [], ALL, 'produce'],
  ['pomegranate', [], ALL, 'produce'],
  ['raspberry', [], ALL, 'produce'],
  ['strawberry', [], ALL, 'produce'],
  ['watermelon', [], ALL, 'produce'],

  // ── Grains & Starches ─────────────────────────────────────────────────────
  ['all-purpose flour', ['gluten'], VEGAN_NO_GF, 'baking-spices'],
  ['barley', ['gluten'], VEGAN_NO_GF, 'dry-pasta-grains'],
  ['basmati rice', [], ALL, 'dry-pasta-grains'],
  ['bread flour', ['gluten'], VEGAN_NO_GF, 'baking-spices'],
  ['breadcrumb', ['gluten'], VEGAN_NO_GF, 'dry-pasta-grains'],
  ['brown rice', [], ALL, 'dry-pasta-grains'],
  ['cornmeal', [], ALL, 'baking-spices'],
  ['cornstarch', [], ALL, 'baking-spices'],
  ['egg noodle', ['gluten', 'eggs'], ['vegetarian', 'pescatarian', 'dairy_free', 'nut_free'], 'dry-pasta-grains'],
  ['farro', ['gluten'], VEGAN_NO_GF, 'dry-pasta-grains'],
  ['fettuccine', ['gluten'], VEGAN_NO_GF, 'dry-pasta-grains'],
  ['flour', ['gluten'], VEGAN_NO_GF, 'baking-spices'],
  ['jasmine rice', [], ALL, 'dry-pasta-grains'],
  ['lasagna noodle', ['gluten'], VEGAN_NO_GF, 'dry-pasta-grains'],
  ['oats', [], ['vegan', 'vegetarian', 'pescatarian', 'dairy_free', 'nut_free'], 'dry-pasta-grains'], // typically not certified GF
  ['panko breadcrumb', ['gluten'], VEGAN_NO_GF, 'dry-pasta-grains'],
  ['pasta', ['gluten'], VEGAN_NO_GF, 'dry-pasta-grains'],
  ['penne', ['gluten'], VEGAN_NO_GF, 'dry-pasta-grains'],
  ['polenta', [], ALL, 'dry-pasta-grains'],
  ['potato starch', [], ALL, 'baking-spices'],
  ['quinoa', [], ALL, 'dry-pasta-grains'],
  ['rice', [], ALL, 'dry-pasta-grains'],
  ['rolled oat', [], ['vegan', 'vegetarian', 'pescatarian', 'dairy_free', 'nut_free'], 'dry-pasta-grains'],
  ['sourdough bread', ['gluten'], VEGAN_NO_GF, 'bakery'],
  ['spaghetti', ['gluten'], VEGAN_NO_GF, 'dry-pasta-grains'],
  ['white rice', [], ALL, 'dry-pasta-grains'],
  ['whole wheat flour', ['gluten'], VEGAN_NO_GF, 'baking-spices'],

  // ── Legumes ───────────────────────────────────────────────────────────────
  ['black bean', [], ALL, 'canned-jarred'],
  ['cannellini bean', [], ALL, 'canned-jarred'],
  ['chickpea', [], ALL, 'canned-jarred'],
  ['edamame', ['soy'], ALL, 'frozen'],
  ['kidney bean', [], ALL, 'canned-jarred'],
  ['lentil', [], ALL, 'dry-pasta-grains'],
  ['pinto bean', [], ALL, 'canned-jarred'],
  ['split pea', [], ALL, 'dry-pasta-grains'],
  ['white bean', [], ALL, 'canned-jarred'],

  // ── Canned & Broths ───────────────────────────────────────────────────────
  ['beef broth', [], MEAT, 'canned-jarred'],
  ['beef stock', [], MEAT, 'canned-jarred'],
  ['chicken broth', [], MEAT, 'canned-jarred'],
  ['chicken stock', [], MEAT, 'canned-jarred'],
  ['coconut cream', [], ALL, 'canned-jarred'],
  ['coconut milk', [], ALL, 'canned-jarred'],
  ['crushed tomato', [], ALL, 'canned-jarred'],
  ['diced tomato', [], ALL, 'canned-jarred'],
  ['tomato paste', [], ALL, 'canned-jarred'],
  ['tomato sauce', [], ALL, 'canned-jarred'],
  ['vegetable broth', [], ALL, 'canned-jarred'],
  ['vegetable stock', [], ALL, 'canned-jarred'],

  // ── Oils & Vinegars ───────────────────────────────────────────────────────
  ['apple cider vinegar', [], ALL, 'condiments-oils'],
  ['balsamic vinegar', [], ALL, 'condiments-oils'],
  ['canola oil', [], ALL, 'condiments-oils'],
  ['coconut oil', [], ALL, 'condiments-oils'],
  ['extra virgin olive oil', [], ALL, 'condiments-oils'],
  ['ghee', ['dairy'], DAIRY, 'condiments-oils'],
  ['olive oil', [], ALL, 'condiments-oils'],
  ['red wine vinegar', [], ALL, 'condiments-oils'],
  ['rice vinegar', [], ALL, 'condiments-oils'],
  ['sesame oil', ['sesame'], ALL, 'condiments-oils'],
  ['vegetable oil', [], ALL, 'condiments-oils'],
  ['white vinegar', [], ALL, 'condiments-oils'],

  // ── Sauces & Condiments ───────────────────────────────────────────────────
  ['agave', [], ALL, 'condiments-oils'],
  ['dijon mustard', [], ALL, 'condiments-oils'],
  ['fish sauce', ['fish'], SEAFOOD, 'condiments-oils'],
  ['hoisin sauce', ['soy', 'gluten'], ['vegan', 'vegetarian', 'pescatarian', 'dairy_free', 'nut_free'], 'condiments-oils'],
  ['honey', [], VEG_PLUS, 'condiments-oils'], // not vegan
  ['hot sauce', [], ALL, 'condiments-oils'],
  ['ketchup', [], ALL, 'condiments-oils'],
  ['maple syrup', [], ALL, 'condiments-oils'],
  ['mayonnaise', ['eggs'], EGG, 'condiments-oils'],
  ['miso paste', ['soy'], ['vegan', 'vegetarian', 'pescatarian', 'dairy_free', 'nut_free'], 'condiments-oils'], // may have barley
  ['mustard', [], ALL, 'condiments-oils'],
  ['oyster sauce', ['shellfish', 'soy', 'gluten'], ['pescatarian', 'dairy_free', 'nut_free'], 'condiments-oils'],
  ['soy sauce', ['soy', 'gluten'], VEGAN_NO_GF, 'condiments-oils'],
  ['sriracha', [], ALL, 'condiments-oils'],
  ['tahini', ['sesame'], ALL, 'condiments-oils'],
  ['tamari', ['soy'], ALL, 'condiments-oils'], // typically wheat-free
  ['worcestershire sauce', ['fish'], SEAFOOD, 'condiments-oils'],

  // ── Spices & Herbs ────────────────────────────────────────────────────────
  ['allspice', [], ALL, 'baking-spices'],
  ['basil', [], ALL, 'produce'],
  ['bay leaf', [], ALL, 'baking-spices'],
  ['black pepper', [], ALL, 'baking-spices'],
  ['cardamom', [], ALL, 'baking-spices'],
  ['cayenne pepper', [], ALL, 'baking-spices'],
  ['chili powder', [], ALL, 'baking-spices'],
  ['chive', [], ALL, 'produce'],
  ['cilantro', [], ALL, 'produce'],
  ['cinnamon', [], ALL, 'baking-spices'],
  ['clove', [], ALL, 'baking-spices'],
  ['coriander', [], ALL, 'produce'],
  ['cumin', [], ALL, 'baking-spices'],
  ['curry powder', [], ALL, 'baking-spices'],
  ['dill', [], ALL, 'produce'],
  ['fresh ginger', [], ALL, 'produce'],
  ['garam masala', [], ALL, 'baking-spices'],
  ['garlic powder', [], ALL, 'baking-spices'],
  ['ginger', [], ALL, 'produce'],
  ['ground cinnamon', [], ALL, 'baking-spices'],
  ['ground coriander', [], ALL, 'baking-spices'],
  ['ground cumin', [], ALL, 'baking-spices'],
  ['ground ginger', [], ALL, 'baking-spices'],
  ['italian seasoning', [], ALL, 'baking-spices'],
  ['kosher salt', [], ALL, 'baking-spices'],
  ['marjoram', [], ALL, 'baking-spices'],
  ['mint', [], ALL, 'produce'],
  ['nutmeg', [], ALL, 'baking-spices'],
  ['onion powder', [], ALL, 'baking-spices'],
  ['oregano', [], ALL, 'baking-spices'],
  ['paprika', [], ALL, 'baking-spices'],
  ['parsley', [], ALL, 'produce'],
  ['red pepper flake', [], ALL, 'baking-spices'],
  ['rosemary', [], ALL, 'produce'],
  ['sage', [], ALL, 'produce'],
  ['salt', [], ALL, 'baking-spices'],
  ['sea salt', [], ALL, 'baking-spices'],
  ['smoked paprika', [], ALL, 'baking-spices'],
  ['tarragon', [], ALL, 'produce'],
  ['thyme', [], ALL, 'produce'],
  ['turmeric', [], ALL, 'baking-spices'],
  ['white pepper', [], ALL, 'baking-spices'],

  // ── Baking ────────────────────────────────────────────────────────────────
  ['active dry yeast', [], ALL, 'baking-spices'],
  ['almond extract', ['tree_nuts'], NUTS, 'baking-spices'],
  ['baking powder', [], ALL, 'baking-spices'],
  ['baking soda', [], ALL, 'baking-spices'],
  ['brown sugar', [], ALL, 'baking-spices'],
  ['caster sugar', [], ALL, 'baking-spices'],
  ['chocolate chip', ['dairy'], DAIRY, 'baking-spices'],
  ['cocoa powder', [], ALL, 'baking-spices'],
  ['cream of tartar', [], ALL, 'baking-spices'],
  ['dark chocolate', ['dairy'], DAIRY, 'baking-spices'],
  ['gelatin', [], ['pescatarian', 'gluten_free', 'dairy_free', 'nut_free'], 'baking-spices'], // animal product; not vegetarian
  ['powdered sugar', [], ALL, 'baking-spices'],
  ['semi-sweet chocolate', ['dairy'], DAIRY, 'baking-spices'],
  ['sugar', [], ALL, 'baking-spices'],
  ['vanilla bean', [], ALL, 'baking-spices'],
  ['vanilla extract', [], ALL, 'baking-spices'],
  ['yeast', [], ALL, 'baking-spices'],

  // ── Nuts & Seeds ──────────────────────────────────────────────────────────
  ['almond', ['tree_nuts'], NUTS, 'snacks'],
  ['almond butter', ['tree_nuts'], NUTS, 'condiments-oils'],
  ['cashew', ['tree_nuts'], NUTS, 'snacks'],
  ['chia seed', [], ALL, 'snacks'],
  ['flaxseed', [], ALL, 'snacks'],
  ['hazelnut', ['tree_nuts'], NUTS, 'snacks'],
  ['peanut', ['peanuts'], NUTS, 'snacks'],
  ['peanut butter', ['peanuts'], NUTS, 'condiments-oils'],
  ['pecan', ['tree_nuts'], NUTS, 'snacks'],
  ['pine nut', ['tree_nuts'], NUTS, 'snacks'],
  ['pumpkin seed', [], ALL, 'snacks'],
  ['sesame seed', ['sesame'], ALL, 'snacks'],
  ['sunflower seed', [], ALL, 'snacks'],
  ['walnut', ['tree_nuts'], NUTS, 'snacks'],

  // ── Other ─────────────────────────────────────────────────────────────────
  ['beer', ['gluten'], VEGAN_NO_GF, 'beverages'],
  ['lemon juice', [], ALL, 'produce'],
  ['lime juice', [], ALL, 'produce'],
  ['orange juice', [], ALL, 'beverages'],
  ['red wine', [], ALL, 'beverages'],
  ['water', [], ALL, 'household-other'],
  ['white wine', [], ALL, 'beverages'],
];
