// Each entry: [canonical lowercase name, allergens[], compatible diets[]]
// "compatible diets" = diets this ingredient does NOT disqualify
// Allergen and diet values must match ALLERGENS / DIETS constants.

type Entry = [string, string[], string[]];

const ALL: string[] = ['vegan', 'vegetarian', 'pescatarian', 'gluten_free', 'dairy_free', 'nut_free'];
const VEG_PLUS: string[] = ['vegetarian', 'pescatarian', 'gluten_free', 'dairy_free', 'nut_free']; // not vegan (honey, eggs, etc.)
const VEGAN_NO_GF: string[] = ['vegan', 'vegetarian', 'pescatarian', 'dairy_free', 'nut_free']; // vegan but contains gluten
const MEAT: string[] = ['gluten_free', 'dairy_free', 'nut_free']; // land meat
const SEAFOOD: string[] = ['pescatarian', 'gluten_free', 'dairy_free', 'nut_free']; // fish/shellfish
const DAIRY: string[] = ['vegetarian', 'pescatarian', 'gluten_free', 'nut_free']; // dairy (not vegan/dairy_free)
const EGG: string[] = ['vegetarian', 'pescatarian', 'gluten_free', 'dairy_free', 'nut_free']; // eggs
const NUTS: string[] = ['vegan', 'vegetarian', 'pescatarian', 'gluten_free', 'dairy_free']; // tree nuts / peanuts (not nut_free)

export const INGREDIENT_CATALOG: Entry[] = [
  // ── Proteins ──────────────────────────────────────────────────────────────
  ['bacon', [], MEAT],
  ['beef steak', [], MEAT],
  ['chicken breast', [], MEAT],
  ['chicken thighs', [], MEAT],
  ['chicken wings', [], MEAT],
  ['crab', ['shellfish'], SEAFOOD],
  ['eggs', ['eggs'], EGG],
  ['ground beef', [], MEAT],
  ['ground pork', [], MEAT],
  ['ground turkey', [], MEAT],
  ['ham', [], MEAT],
  ['lamb chops', [], MEAT],
  ['lobster', ['shellfish'], SEAFOOD],
  ['pork chops', [], MEAT],
  ['pork loin', [], MEAT],
  ['salmon', ['fish'], SEAFOOD],
  ['sausage', [], ['dairy_free', 'nut_free']], // may contain gluten fillers; not vegetarian
  ['shrimp', ['shellfish'], SEAFOOD],
  ['tempeh', ['soy'], ALL],
  ['tilapia', ['fish'], SEAFOOD],
  ['tofu', ['soy'], ALL],
  ['tuna', ['fish'], SEAFOOD],
  ['turkey breast', [], MEAT],

  // ── Dairy ─────────────────────────────────────────────────────────────────
  ['butter', ['dairy'], DAIRY],
  ['cheddar cheese', ['dairy'], DAIRY],
  ['cottage cheese', ['dairy'], DAIRY],
  ['cream cheese', ['dairy'], DAIRY],
  ['feta cheese', ['dairy'], DAIRY],
  ['goat cheese', ['dairy'], DAIRY],
  ['greek yogurt', ['dairy'], DAIRY],
  ['gruyere cheese', ['dairy'], DAIRY],
  ['half and half', ['dairy'], DAIRY],
  ['heavy cream', ['dairy'], DAIRY],
  ['milk', ['dairy'], DAIRY],
  ['mozzarella cheese', ['dairy'], DAIRY],
  ['parmesan cheese', ['dairy'], DAIRY],
  ['ricotta cheese', ['dairy'], DAIRY],
  ['sour cream', ['dairy'], DAIRY],
  ['whole milk', ['dairy'], DAIRY],
  ['yogurt', ['dairy'], DAIRY],

  // ── Vegetables ────────────────────────────────────────────────────────────
  ['artichoke', [], ALL],
  ['arugula', [], ALL],
  ['asparagus', [], ALL],
  ['avocado', [], ALL],
  ['beet', [], ALL],
  ['bell pepper', [], ALL],
  ['broccoli', [], ALL],
  ['brussels sprouts', [], ALL],
  ['butternut squash', [], ALL],
  ['cabbage', [], ALL],
  ['carrot', [], ALL],
  ['cauliflower', [], ALL],
  ['celery', [], ALL],
  ['cherry tomato', [], ALL],
  ['chili pepper', [], ALL],
  ['corn', [], ALL],
  ['cucumber', [], ALL],
  ['eggplant', [], ALL],
  ['fennel', [], ALL],
  ['garlic', [], ALL],
  ['green bean', [], ALL],
  ['green bell pepper', [], ALL],
  ['green onion', [], ALL],
  ['iceberg lettuce', [], ALL],
  ['jalapeño', [], ALL],
  ['kale', [], ALL],
  ['leek', [], ALL],
  ['mushroom', [], ALL],
  ['onion', [], ALL],
  ['pea', [], ALL],
  ['portobello mushroom', [], ALL],
  ['potato', [], ALL],
  ['radish', [], ALL],
  ['red bell pepper', [], ALL],
  ['red onion', [], ALL],
  ['romaine lettuce', [], ALL],
  ['shallot', [], ALL],
  ['shiitake mushroom', [], ALL],
  ['spinach', [], ALL],
  ['squash', [], ALL],
  ['sweet potato', [], ALL],
  ['tomato', [], ALL],
  ['yellow onion', [], ALL],
  ['zucchini', [], ALL],

  // ── Fruits ────────────────────────────────────────────────────────────────
  ['apple', [], ALL],
  ['banana', [], ALL],
  ['blackberry', [], ALL],
  ['blueberry', [], ALL],
  ['cantaloupe', [], ALL],
  ['grape', [], ALL],
  ['lemon', [], ALL],
  ['lime', [], ALL],
  ['mango', [], ALL],
  ['orange', [], ALL],
  ['peach', [], ALL],
  ['pear', [], ALL],
  ['pineapple', [], ALL],
  ['pomegranate', [], ALL],
  ['raspberry', [], ALL],
  ['strawberry', [], ALL],
  ['watermelon', [], ALL],

  // ── Grains & Starches ─────────────────────────────────────────────────────
  ['all-purpose flour', ['gluten'], VEGAN_NO_GF],
  ['barley', ['gluten'], VEGAN_NO_GF],
  ['basmati rice', [], ALL],
  ['bread flour', ['gluten'], VEGAN_NO_GF],
  ['breadcrumb', ['gluten'], VEGAN_NO_GF],
  ['brown rice', [], ALL],
  ['cornmeal', [], ALL],
  ['cornstarch', [], ALL],
  ['egg noodle', ['gluten', 'eggs'], ['vegetarian', 'pescatarian', 'dairy_free', 'nut_free']],
  ['farro', ['gluten'], VEGAN_NO_GF],
  ['fettuccine', ['gluten'], VEGAN_NO_GF],
  ['flour', ['gluten'], VEGAN_NO_GF],
  ['jasmine rice', [], ALL],
  ['lasagna noodle', ['gluten'], VEGAN_NO_GF],
  ['oats', [], ['vegan', 'vegetarian', 'pescatarian', 'dairy_free', 'nut_free']], // typically not certified GF
  ['panko breadcrumb', ['gluten'], VEGAN_NO_GF],
  ['pasta', ['gluten'], VEGAN_NO_GF],
  ['penne', ['gluten'], VEGAN_NO_GF],
  ['polenta', [], ALL],
  ['potato starch', [], ALL],
  ['quinoa', [], ALL],
  ['rice', [], ALL],
  ['rolled oat', [], ['vegan', 'vegetarian', 'pescatarian', 'dairy_free', 'nut_free']],
  ['sourdough bread', ['gluten'], VEGAN_NO_GF],
  ['spaghetti', ['gluten'], VEGAN_NO_GF],
  ['white rice', [], ALL],
  ['whole wheat flour', ['gluten'], VEGAN_NO_GF],

  // ── Legumes ───────────────────────────────────────────────────────────────
  ['black bean', [], ALL],
  ['cannellini bean', [], ALL],
  ['chickpea', [], ALL],
  ['edamame', ['soy'], ALL],
  ['kidney bean', [], ALL],
  ['lentil', [], ALL],
  ['pinto bean', [], ALL],
  ['split pea', [], ALL],
  ['white bean', [], ALL],

  // ── Canned & Broths ───────────────────────────────────────────────────────
  ['beef broth', [], MEAT],
  ['beef stock', [], MEAT],
  ['chicken broth', [], MEAT],
  ['chicken stock', [], MEAT],
  ['coconut cream', [], ALL],
  ['coconut milk', [], ALL],
  ['crushed tomato', [], ALL],
  ['diced tomato', [], ALL],
  ['tomato paste', [], ALL],
  ['tomato sauce', [], ALL],
  ['vegetable broth', [], ALL],
  ['vegetable stock', [], ALL],

  // ── Oils & Vinegars ───────────────────────────────────────────────────────
  ['apple cider vinegar', [], ALL],
  ['balsamic vinegar', [], ALL],
  ['canola oil', [], ALL],
  ['coconut oil', [], ALL],
  ['extra virgin olive oil', [], ALL],
  ['ghee', ['dairy'], DAIRY],
  ['olive oil', [], ALL],
  ['red wine vinegar', [], ALL],
  ['rice vinegar', [], ALL],
  ['sesame oil', ['sesame'], ALL],
  ['vegetable oil', [], ALL],
  ['white vinegar', [], ALL],

  // ── Sauces & Condiments ───────────────────────────────────────────────────
  ['agave', [], ALL],
  ['dijon mustard', [], ALL],
  ['fish sauce', ['fish'], SEAFOOD],
  ['hoisin sauce', ['soy', 'gluten'], ['vegan', 'vegetarian', 'pescatarian', 'dairy_free', 'nut_free']],
  ['honey', [], VEG_PLUS], // not vegan
  ['hot sauce', [], ALL],
  ['ketchup', [], ALL],
  ['maple syrup', [], ALL],
  ['mayonnaise', ['eggs'], EGG],
  ['miso paste', ['soy'], ['vegan', 'vegetarian', 'pescatarian', 'dairy_free', 'nut_free']], // may have barley
  ['mustard', [], ALL],
  ['oyster sauce', ['shellfish', 'soy', 'gluten'], ['pescatarian', 'dairy_free', 'nut_free']],
  ['soy sauce', ['soy', 'gluten'], VEGAN_NO_GF],
  ['sriracha', [], ALL],
  ['tahini', ['sesame'], ALL],
  ['tamari', ['soy'], ALL], // typically wheat-free
  ['worcestershire sauce', ['fish'], SEAFOOD],

  // ── Spices & Herbs ────────────────────────────────────────────────────────
  ['allspice', [], ALL],
  ['basil', [], ALL],
  ['bay leaf', [], ALL],
  ['black pepper', [], ALL],
  ['cardamom', [], ALL],
  ['cayenne pepper', [], ALL],
  ['chili powder', [], ALL],
  ['chive', [], ALL],
  ['cilantro', [], ALL],
  ['cinnamon', [], ALL],
  ['clove', [], ALL],
  ['coriander', [], ALL],
  ['cumin', [], ALL],
  ['curry powder', [], ALL],
  ['dill', [], ALL],
  ['fresh ginger', [], ALL],
  ['garam masala', [], ALL],
  ['garlic powder', [], ALL],
  ['ginger', [], ALL],
  ['ground cinnamon', [], ALL],
  ['ground coriander', [], ALL],
  ['ground cumin', [], ALL],
  ['ground ginger', [], ALL],
  ['italian seasoning', [], ALL],
  ['kosher salt', [], ALL],
  ['marjoram', [], ALL],
  ['mint', [], ALL],
  ['nutmeg', [], ALL],
  ['onion powder', [], ALL],
  ['oregano', [], ALL],
  ['paprika', [], ALL],
  ['parsley', [], ALL],
  ['red pepper flake', [], ALL],
  ['rosemary', [], ALL],
  ['sage', [], ALL],
  ['salt', [], ALL],
  ['sea salt', [], ALL],
  ['smoked paprika', [], ALL],
  ['tarragon', [], ALL],
  ['thyme', [], ALL],
  ['turmeric', [], ALL],
  ['white pepper', [], ALL],

  // ── Baking ────────────────────────────────────────────────────────────────
  ['active dry yeast', [], ALL],
  ['almond extract', ['tree_nuts'], NUTS],
  ['baking powder', [], ALL],
  ['baking soda', [], ALL],
  ['brown sugar', [], ALL],
  ['caster sugar', [], ALL],
  ['chocolate chip', ['dairy'], DAIRY],
  ['cocoa powder', [], ALL],
  ['cream of tartar', [], ALL],
  ['dark chocolate', ['dairy'], DAIRY],
  ['gelatin', [], ['pescatarian', 'gluten_free', 'dairy_free', 'nut_free']], // animal product; not vegetarian
  ['powdered sugar', [], ALL],
  ['semi-sweet chocolate', ['dairy'], DAIRY],
  ['sugar', [], ALL],
  ['vanilla bean', [], ALL],
  ['vanilla extract', [], ALL],
  ['yeast', [], ALL],

  // ── Nuts & Seeds ──────────────────────────────────────────────────────────
  ['almond', ['tree_nuts'], NUTS],
  ['almond butter', ['tree_nuts'], NUTS],
  ['cashew', ['tree_nuts'], NUTS],
  ['chia seed', [], ALL],
  ['flaxseed', [], ALL],
  ['hazelnut', ['tree_nuts'], NUTS],
  ['peanut', ['peanuts'], NUTS],
  ['peanut butter', ['peanuts'], NUTS],
  ['pecan', ['tree_nuts'], NUTS],
  ['pine nut', ['tree_nuts'], NUTS],
  ['pumpkin seed', [], ALL],
  ['sesame seed', ['sesame'], ALL],
  ['sunflower seed', [], ALL],
  ['walnut', ['tree_nuts'], NUTS],

  // ── Other ─────────────────────────────────────────────────────────────────
  ['beer', ['gluten'], VEGAN_NO_GF],
  ['lemon juice', [], ALL],
  ['lime juice', [], ALL],
  ['orange juice', [], ALL],
  ['red wine', [], ALL],
  ['water', [], ALL],
  ['white wine', [], ALL],
];
